print("True and True: "True and True) 
print("False and True: "False and True) 
print("1 == 1 and 2 == 1: "1 == 1 and 2 == 1) 
print(""test" == "test": ""test" == "test") 
print("1 == 1 or 2 != 1: "1 == 1 or 2 != 1) 
print("True and 1 == 1: "True and 1 == 1) 
print("False and 0 != 0: "False and 0 != 0) 
print("True or 1 == 1: "True or 1 == 1) 
print(""test" == "testing": ""test" == "testing") 
print("1 != 0 and 2 == 1: "1 != 0 and 2 == 1) 
print(""test" != "testing": ""test" != "testing") 
print(""test" == 1: ""test" == 1) 
print("not (True and False): "not (True and False)) 
print("not (1 == 1 and 0 != 1): "not (1 == 1 and 0 != 1)) 
print("not (10 == 1 and 0 != 1): "not (10 == 1 and 0 != 1)) 
print("not (10 == 1 or 1000 == 1000): "not (10 == 1 or 1000 == 1000)) 
print("not ("testing" == "testing" and "Zed" == "Cool Guy"): "not ("testing" == "testing" and "Zed" == "Cool Guy")) 
print("1 == 1 and (not ("testing == 1 or 1 == 0")): "1 == 1 and (not ("testing == 1 or 1 == 0"))) 
print(""chunky" == "bacon" and (not (3 == 4 or 3 == 3)): ""chunky" == "bacon" and (not (3 == 4 or 3 == 3))) 
print("3 == 3 and (not ("testing" "testing" or "Python" == "Fun")): "3 == 3 and (not ("testing" "testing" or "Python" == "Fun"))) 
print(": ") 
print("# Tips:: "# Tips:) 
print("# 1. Find an equality test (== or !=) and replace it with its truth.: "# 1. Find an equality test (== or !=) and replace it with its truth.) 
print("# 2. Find each and/or inside parentheses and solve those first.: "# 2. Find each and/or inside parentheses and solve those first.) 
print("# 3. Find each not and invert it.: "# 3. Find each not and invert it.) 
print("# 4. Find any remaining and/or and solve it.: "# 4. Find any remaining and/or and solve it.) 
print("# 5. When you are done you should have True or False.: "# 5. When you are done you should have True or False.) 
